import crypto from 'node:crypto';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { spawn } from 'node:child_process';
import { inflateRawSync } from 'node:zlib';

const repoRoot = path.resolve(import.meta.dirname, '..');
const artifactRoot = path.join(repoRoot, 'artifacts');
const evidenceRoot = path.join(repoRoot, 'verification', 'evidence');
const attachments = ['输入数据包.zip', 'reference.zip', '关键标准答案.xlsx', '任务规格转化.xlsx'];
const expectedOutputs = ['output/reports/moderation_actions.csv','output/reports/receipt_gaps.csv','output/reports/room_summary.csv','output/reports/room_transcripts.ndjson','output/scripts/rebuild_chat_transcripts.mjs'].sort();
const csvKeys = {
  'output/reports/moderation_actions.csv': ['room_id','msg_id','rule_id'],
  'output/reports/receipt_gaps.csv': ['room_id','msg_id','missing_recipient_id'],
  'output/reports/room_summary.csv': ['room_id'],
};
const assert = (value, message) => { if (!value) throw new Error(message); };
const sha256 = (bytes) => crypto.createHash('sha256').update(bytes).digest('hex');
const sha256File = (file) => sha256(fs.readFileSync(file));

function zipEntries(file) {
  const data = fs.readFileSync(file); let eocd = -1;
  for (let index = data.length - 22; index >= Math.max(0, data.length - 65_557); index -= 1) if (data.readUInt32LE(index) === 0x06054b50) { eocd = index; break; }
  assert(eocd >= 0, `找不到ZIP目录：${file}`);
  const count = data.readUInt16LE(eocd + 10); let offset = data.readUInt32LE(eocd + 16); const entries = new Map();
  for (let entryIndex = 0; entryIndex < count; entryIndex += 1) {
    assert(data.readUInt32LE(offset) === 0x02014b50, `ZIP目录损坏：${file}`);
    const method = data.readUInt16LE(offset + 10); const compressedSize = data.readUInt32LE(offset + 20); const uncompressedSize = data.readUInt32LE(offset + 24);
    const nameLength = data.readUInt16LE(offset + 28); const extraLength = data.readUInt16LE(offset + 30); const commentLength = data.readUInt16LE(offset + 32); const localOffset = data.readUInt32LE(offset + 42);
    const name = data.subarray(offset + 46, offset + 46 + nameLength).toString('utf8').replaceAll('\\','/'); const localNameLength = data.readUInt16LE(localOffset + 26); const localExtraLength = data.readUInt16LE(localOffset + 28); const start = localOffset + 30 + localNameLength + localExtraLength;
    if (!name.endsWith('/')) { const compressed = data.subarray(start, start + compressedSize); const body = method === 0 ? compressed : method === 8 ? inflateRawSync(compressed) : null; assert(body && body.length === uncompressedSize, `无法解压${name}`); entries.set(name, body); }
    offset += 46 + nameLength + extraLength + commentLength;
  }
  return entries;
}
async function extract(file,destination){for(const [name,bytes] of zipEntries(file)){const target=path.resolve(destination,...name.split('/'));assert(target.startsWith(`${path.resolve(destination)}${path.sep}`),`非法ZIP路径：${name}`);await fsp.mkdir(path.dirname(target),{recursive:true});await fsp.writeFile(target,bytes);}}
function workbookSheets(file){const xml=zipEntries(file).get('xl/workbook.xml')?.toString('utf8')??'';return [...xml.matchAll(/<(?:[A-Za-z]+:)?sheet[^>]+name="([^"]+)"/gu)].map((match)=>match[1]);}
async function run(command,args,cwd){const started=Date.now();return await new Promise((resolve)=>{let child;try{child=spawn(command,args,{cwd,env:process.env,windowsHide:true});}catch(error){resolve({code:1,stdout:'',stderr:error.stack??error.message,elapsed_ms:Date.now()-started});return;}let stdout='';let stderr='';let settled=false;child.stdout.on('data',(chunk)=>{stdout+=chunk;});child.stderr.on('data',(chunk)=>{stderr+=chunk;});child.on('error',(error)=>{if(!settled){settled=true;resolve({code:1,stdout,stderr:`${stderr}${error.stack??error.message}`,elapsed_ms:Date.now()-started});}});child.on('exit',(code)=>{if(!settled){settled=true;resolve({code:code??1,stdout,stderr,elapsed_ms:Date.now()-started});}});});}
function parseCsv(text){const rows=[];let row=[];let cell='';let quoted=false;for(let index=0;index<text.length;index+=1){const char=text[index];if(quoted){if(char==='"'&&text[index+1]==='"'){cell+='"';index+=1;}else if(char==='"')quoted=false;else cell+=char;}else if(char==='"')quoted=true;else if(char===','){row.push(cell);cell='';}else if(char==='\n'){row.push(cell.replace(/\r$/u,''));rows.push(row);row=[];cell='';}else cell+=char;}if(cell||row.length){row.push(cell.replace(/\r$/u,''));rows.push(row);}const headers=rows.shift()??[];return rows.filter((values)=>values.some((value)=>value!=='')).map((values)=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])));}
function normalizedCsv(file,text){const keys=csvKeys[file];return parseCsv(text).toSorted((left,right)=>keys.map((key)=>String(left[key]).localeCompare(String(right[key]),'en')).find((value)=>value!==0)??0);}
function normalizedNdjson(text){return text.trim().split(/\r?\n/u).filter(Boolean).map((line)=>JSON.parse(line)).toSorted((left,right)=>`${left.room_id}|${left.msg_id}`.localeCompare(`${right.room_id}|${right.msg_id}`,'en'));}
function files(root){const result=[];function walk(current,prefix=''){if(!fs.existsSync(current))return;for(const entry of fs.readdirSync(current,{withFileTypes:true}).toSorted((left,right)=>left.name.localeCompare(right.name,'en'))){const relative=prefix?`${prefix}/${entry.name}`:entry.name;if(entry.isDirectory())walk(path.join(current,entry.name),relative);else result.push(relative);}}walk(root);return result.sort();}
function treeDigest(root,ignored=new Set()){const lines=[];function walk(current,prefix=''){for(const entry of fs.readdirSync(current,{withFileTypes:true}).toSorted((left,right)=>left.name.localeCompare(right.name,'en'))){const relative=prefix?`${prefix}/${entry.name}`:entry.name;if(ignored.has(relative.split('/')[0]))continue;const full=path.join(current,entry.name);if(entry.isDirectory())walk(full,relative);else lines.push(`${relative}\0${sha256File(full)}`);}}walk(root);return sha256(Buffer.from(lines.join('\n')));}
function classifyExecutable(name,bytes){const lower=name.toLowerCase();if(bytes.length>=4&&bytes[0]===0x7f&&bytes.subarray(1,4).toString('ascii')==='ELF')return'linux_elf';if(/\.(?:sh|bash|so)(?:\.|$)/u.test(lower))return'posix_member';if(/^#!.*(?:ba|z|k)?sh/mu.test(bytes.subarray(0,160).toString('utf8')))return'posix_shebang';return null;}
async function prepare(label,mutate){const root=path.join(os.tmpdir(),label);await fsp.rm(root,{recursive:true,force:true});await fsp.mkdir(root,{recursive:true});await extract(path.join(artifactRoot,'输入数据包.zip'),root);const inputRoot=path.join(root,'input_data');const standard=zipEntries(path.join(artifactRoot,'reference.zip'));const outputRoot=path.join(root,'output');await fsp.mkdir(path.join(outputRoot,'scripts'),{recursive:true});await fsp.writeFile(path.join(outputRoot,'scripts','rebuild_chat_transcripts.mjs'),standard.get('output/scripts/rebuild_chat_transcripts.mjs'));if(mutate)await mutate(inputRoot);return{inputRoot,outputRoot,standard};}
async function execute(room){return await run(process.execPath,[path.join(room.inputRoot,'tools','run-task.mjs')],room.inputRoot);}
function compareStandard(room){const actualPaths=files(room.outputRoot).map((name)=>`output/${name}`);assert(JSON.stringify(actualPaths)===JSON.stringify(expectedOutputs),`输出成员不一致：${actualPaths.join(',')}`);const sourceActual=fs.readFileSync(path.join(room.outputRoot,'scripts','rebuild_chat_transcripts.mjs'),'utf8').replaceAll('\r\n','\n');const sourceExpected=room.standard.get('output/scripts/rebuild_chat_transcripts.mjs').toString('utf8').replaceAll('\r\n','\n');assert(sourceActual===sourceExpected,'完成版程序与标准交付不一致');const normalized={};for(const file of Object.keys(csvKeys)){const actual=normalizedCsv(file,fs.readFileSync(path.join(room.outputRoot,...file.split('/').slice(1)),'utf8'));const expected=normalizedCsv(file,room.standard.get(file).toString('utf8'));assert(JSON.stringify(actual)===JSON.stringify(expected),`${file}业务字段不一致`);normalized[file]=actual;}const ndjsonFile='output/reports/room_transcripts.ndjson';const actualNdjson=normalizedNdjson(fs.readFileSync(path.join(room.outputRoot,'reports','room_transcripts.ndjson'),'utf8'));const expectedNdjson=normalizedNdjson(room.standard.get(ndjsonFile).toString('utf8'));assert(JSON.stringify(actualNdjson)===JSON.stringify(expectedNdjson),'房间转写业务字段不一致');normalized[ndjsonFile]=actualNdjson;return sha256(Buffer.from(JSON.stringify(normalized)));}

await fsp.rm(evidenceRoot,{recursive:true,force:true});await fsp.mkdir(evidenceRoot,{recursive:true});assert(process.platform==='win32'&&process.env.GITHUB_ACTIONS==='true','只接受GitHub托管Windows运行');assert(/^v24\./u.test(process.version),`需要Node.js24，当前为${process.version}`);
const attachmentSha256=Object.fromEntries(attachments.map((name)=>[name,sha256File(path.join(artifactRoot,name))]));const inputMembers=zipEntries(path.join(artifactRoot,'输入数据包.zip'));const standardMembers=[...zipEntries(path.join(artifactRoot,'reference.zip')).keys()].sort();const executableScan=[...inputMembers].map(([name,bytes])=>({name,classification:classifyExecutable(name,bytes)})).filter((item)=>item.classification);assert(executableScan.length===0,`输入包含平台专用成员：${JSON.stringify(executableScan)}`);assert(JSON.stringify(standardMembers)===JSON.stringify(expectedOutputs),'标准交付成员错误');assert(JSON.stringify(workbookSheets(path.join(artifactRoot,'关键标准答案.xlsx')))===JSON.stringify(['交付物答案清单','固定字段答案','固定集合答案','固定数值答案','允许变体答案']),'关键标准答案Sheet错误');assert(JSON.stringify(workbookSheets(path.join(artifactRoot,'任务规格转化.xlsx')))===JSON.stringify(['任务规格转化']),'任务规格Sheet错误');
const completedProgram=zipEntries(path.join(artifactRoot,'reference.zip')).get('output/scripts/rebuild_chat_transcripts.mjs').toString('utf8');assert(!/\b(?:R-OPS|R-SELLER|R-TRUST|M-(?:OPS|SEL|TRU)-\d+|MOD-\d+|GAP-\d+)\b/u.test(completedProgram),'完成版程序含样例房间或消息主键硬编码');const staticReview=JSON.parse(fs.readFileSync(path.join(repoRoot,'qa','static-review.json'),'utf8'));const scoreAnswerLeak=JSON.parse(fs.readFileSync(path.join(repoRoot,'qa','score-answer-leak.json'),'utf8'));const candidateScore=fs.readFileSync(path.join(repoRoot,'task','评分表.txt'),'utf8');const scoreLeakPatterns=[/\b(?:R-(?:OPS|SELLER|TRUST)|M-(?:OPS|SEL|TRU)-\d+|U\d{3}|MOD-\d+|GAP-\d+)\b/giu,/\bRULE-(?:SECRET|PHONE|POLICY|CONTACT)\b/gu,/(?:完整|全部)(?:通过|拒绝|结果|缺口)(?:集合|清单)/gu,/(?:固定|共计|总计|恰好|正好)\s*\d+\s*(?:行|条|组|个|份|项|房间|消息|回执)/gu];const currentScoreLeakHits=scoreLeakPatterns.flatMap((pattern)=>[...candidateScore.matchAll(pattern)].map((match)=>match[0]));assert(staticReview.result==='PASS'&&staticReview.task_spec_column_count===2&&staticReview.humanizer_score>=45,'静态审计、任务规格或语言分不合格');assert(scoreAnswerLeak.pass===true&&scoreAnswerLeak.hit_count===0&&currentScoreLeakHits.length===0,`候选人评分表泄露样本答案：${JSON.stringify(currentScoreLeakHits)}`);
const cleanRuns=[];for(const label of ['Q10428 第一处 中文 空格目录','Q10428 第二处 中文 路径']){const room=await prepare(label);const before=treeDigest(room.inputRoot,new Set(['output']));const execution=await execute(room);assert(execution.code===0,`${label}处理失败\n${execution.stdout}\n${execution.stderr}`);const after=treeDigest(room.inputRoot,new Set(['output']));assert(before===after,`${label}修改了业务输入`);const semanticDigest=compareStandard(room);cleanRuns.push({directory_label:label,exit_code:execution.code,elapsed_ms:execution.elapsed_ms,input_digest_before:before,input_digest_after:after,semantic_digest:semanticDigest,standard_match:true});}assert(cleanRuns[0].semantic_digest===cleanRuns[1].semantic_digest,'两个目录的结构化结果不一致');
const crlf=await prepare('Q10428 CRLF 投递回执',async(inputRoot)=>{const file=path.join(inputRoot,'receipt_log.csv');await fsp.writeFile(file,(await fsp.readFile(file,'utf8')).replace(/\r?\n/gu,'\r\n'));});let execution=await execute(crlf);assert(execution.code===0,`CRLF输入处理失败\n${execution.stdout}\n${execution.stderr}`);const crlfDigest=compareStandard(crlf);assert(crlfDigest===cleanRuns[0].semantic_digest,'CRLF输入改变业务结果');
const mutation=await prepare('Q10428 遮盖替换变化',async(inputRoot)=>{const file=path.join(inputRoot,'moderation_rules.json');const rules=JSON.parse(await fsp.readFile(file,'utf8'));const target=rules.find((row)=>row.rule_id==='RULE-PHONE');assert(target,'找不到电话遮盖规则');target.replacement='[phone-withheld]';await fsp.writeFile(file,`${JSON.stringify(rules,null,2)}\n`);});execution=await execute(mutation);assert(execution.code===0,`遮盖规则变化后处理失败\n${execution.stdout}\n${execution.stderr}`);const changedTranscripts=normalizedNdjson(await fsp.readFile(path.join(mutation.outputRoot,'reports','room_transcripts.ndjson'),'utf8'));const changedMessage=changedTranscripts.find((row)=>row.moderation_flags.includes('RULE-PHONE'));assert(changedMessage?.final_text_masked.includes('[phone-withheld]'),'遮盖替换未联动转写');const changedActions=parseCsv(await fsp.readFile(path.join(mutation.outputRoot,'reports','moderation_actions.csv'),'utf8'));assert(changedActions.some((row)=>row.rule_id==='RULE-PHONE'&&row.replacement==='[phone-withheld]'),'遮盖替换未联动动作报告');
const invalid=await prepare('Q10428 无效成员输入',async(inputRoot)=>{await fsp.rm(path.join(inputRoot,'room_members.csv'));});execution=await execute(invalid);const invalidReportsAbsent=!fs.existsSync(path.join(invalid.outputRoot,'reports'));const invalidSolutionPreserved=fs.existsSync(path.join(invalid.outputRoot,'scripts','rebuild_chat_transcripts.mjs'));assert(execution.code!==0&&invalidReportsAbsent&&invalidSolutionPreserved,'无效输入没有中止处理或污染完成程序');
const evidence={schema_version:1,task_asset_id:'node_chat_shard_transcript_reconciliation',result:'PASS',generated_at_utc:new Date().toISOString(),git_commit_sha:process.env.GITHUB_SHA,workflow_run_id:process.env.GITHUB_RUN_ID,runner:{os:process.env.RUNNER_OS,arch:process.env.RUNNER_ARCH,image_os:process.env.ImageOS,image_version:process.env.ImageVersion,node:process.version,actual_windows_run:true,powershell_hosted_workflow:true},software:{node:process.version,entry:'npm run process'},attachment_sha256:attachmentSha256,archive_checks:{input_members:[...inputMembers.keys()].sort(),standard_output_members:standardMembers,prohibited_platform_members:executableScan},workbook_checks:{answer_sheet_names:workbookSheets(path.join(artifactRoot,'关键标准答案.xlsx')),specification_sheet_names:workbookSheets(path.join(artifactRoot,'任务规格转化.xlsx')),task_spec_column_count:staticReview.task_spec_column_count,candidate_score_answer_leak_hits:currentScoreLeakHits.length},clean_runs:cleanRuns,crlf_case:{changed_input:'receipt_log.csv行尾改为CRLF',exit_code:0,semantic_digest:crlfDigest,standard_match:true},positive_business_change:{changed_rule:'RULE-PHONE的replacement改为[phone-withheld]',exit_code:0,changed_message_key:`${changedMessage.room_id}/${changedMessage.msg_id}`,changed_text:changedMessage.final_text_masked},invalid_input:{removed_input:'room_members.csv',exit_code:execution.code,reports_absent:invalidReportsAbsent,solution_preserved:invalidSolutionPreserved},network:{formal_run_access:'none'}};
await fsp.writeFile(path.join(evidenceRoot,'windows-verification.json'),`${JSON.stringify(evidence,null,2)}\n`);await fsp.writeFile(path.join(evidenceRoot,'windows-audit.json'),`${JSON.stringify({schema_version:1,task_asset_id:evidence.task_asset_id,result:evidence.result,platform:process.platform,node_version:process.version,attachment_sha256:attachmentSha256,clean_directory_count:cleanRuns.length,crlf_pass:true,positive_business_change_pass:true,invalid_input_pass:true},null,2)}\n`);console.log(JSON.stringify(evidence,null,2));
